In [21]:
from dwave.system import DWaveSampler, EmbeddingComposite

In [22]:
Q = {('x1', 'x1'): 2, ('x2', 'x2'): 2, ('x1', 'x2'): 1, ('x1', 'z'): -3, ('x2', 'z'): -3, ('z', 'z'): 1}
sampler = DWaveSampler()
sampler_embedded = EmbeddingComposite(sampler)

In [24]:
sampleset = sampler_embedded.sample_qubo(Q, num_reads=50)
print(sampleset)

SolverFailureError: Problem not accepted because user oksanichenko.fedor@mail.ru has insufficient remaining solver access time in project DEV

In [5]:
Q = {('x1', 'x1'): 2, ('x2', 'x2'): 2, ('x1', 'x2'): -1, ('x1', 'z'): -1, ('x2', 'z'): -1, ('z', 'z'): 2}
sampler = DWaveSampler()
sampler_embedded = EmbeddingComposite(sampler)


In [6]:
sampleset = sampler_embedded.sample_qubo(Q, num_reads=500)
print(sampleset)

  x1 x2  z energy num_oc. chain_.
0  0  0  0    0.0     500     0.0
['BINARY', 1 rows, 500 samples, 3 variables]


In [32]:
import numpy as np
A = np.array([[1,2,3],[3,4,3]])
print((A[0]).reshape(1,3))
print(np.dot((A[0]).reshape(3,1),(A[0]).reshape(1,3)))
B = np.zeros((10,10))
for i in range(10):
    for j in range(i+1,10):
        B[i,j] = 1
print(B)

[[1 2 3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
